config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#roadmap'
  get '/roadmap', to: 'static_pages#roadmap'

  namespace :admin do
    root to: 'boards#index'

    resources :boards
    resources :comments
    resources :posts
    resources :post_statuses
    resources :users
  end
  
  devise_for :users

  resources :posts, only: [:index, :create, :show, :update] do
    resource :likes, only: [:create, :destroy]
    resources :likes, only: [:index]
    resources :comments, only: [:index, :create, :update]
  end
  resources :boards, only: [:show]
  resources :post_statuses, only: [:index]
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice container alert alert-primary"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert container alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_boards_menu_section.html.erb
<% boards.each do |board| %>
  <li class="nav-item<%= board.id == @board.id ? ' active' : '' unless @board.nil? %>">
    <%= link_to board.name, board_path(board), class: 'nav-link' %>
  </li>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light">
  <div class="container">
    <%=
      link_to root_path, class: 'navbar-brand' do
        app_name = content_tag :span, Rails.application.name
        logo = image_tag(asset_pack_path('media/images/logo.png'), class: 'logo')

        Rails.application.show_logo? ? logo + app_name : app_name
      end
    %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="boardsNav navbar-nav mr-auto">
        <%= render 'layouts/boards_menu_section', boards: @boards unless @boards.nil? %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <% if current_user.power_user? %>
            <li class="nav-item">
              <%= link_to 'Admin Panel', admin_root_path, class: 'nav-link', 'data-turbolinks': 'false' %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag(current_user.gravatar_url, class: 'gravatar', alt: current_user.full_name, size: 24) %>
              <span class="fullname"><%= current_user.full_name %></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Profile settings', edit_user_registration_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in / Sign up', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.application.name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_pack_path('media/images/favicon.png') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/alerts' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>